#version: '3.0'
#services:
#  rasa:
#    image: rasa/rasa:1.10.10-full
#    ports:
#      - 5005:5005
#    volumes:
#      - ./:/app
#    command:
#      - run
#  action_server:
#    image: rasa/rasa-sdk:latest
#    volumes:
#      - ./actions:/app/actions

version: '3'
services:
  rasa:
    container_name: rasa-server
    image: rasa/rasa:1.10.10-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
      - --cors
      - "*"
      - --enable-api
      - --log-file
      - out.log
    depends_on:
      - action-server
  action-server:
    container_name: rasa-action-server
    image: rasa/rasa-sdk:latest
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"